pipeline:
  name: nodejs-pipeline
  identifier: nodejspipeline
  projectIdentifier: Nodejs_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Prasanth-sekharan/Simple-Node-App
        build: <+input>
  stages:
    - stage:
        name: nodejs-build
        identifier: nodejsbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: dockerhub_connector
                    image: prasanthsekharan/harness
        delegateSelectors:
          - windows-amd64
