pipeline:
  name: nodejs-pipeline
  identifier: nodejspipeline
  projectIdentifier: Nodejs_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Prasanth-sekharan/Simple-Node-App
        build: <+input>
  stages:
    - stage:
        name: nodejs-build
        identifier: nodejsbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub_connector
                    repo: prasanthsekharan/harness
                    tags:
                      - v1
